export const types = {
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_ERROR:'LOGIN_ERROR',
    LOGIN_REQUEST:'LOGIN_REQUEST',

    LOGIN_VALIDATION_SUCCESS:'LOGIN_VALIDATION_SUCCESS',
    LOGIN_VALIDATION_ERROR:'LOGIN_VALIDATION_ERROR',

    GET_USER: 'GET_USER',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_ERROR: 'GET_USER_ERROR',
    SEARCH_USER: 'SEARCH_USER',
    SEARCH_USER_SUCCESS: 'SEARCH_USER_SUCCESS',
    SEARCH_USER_ERROR: 'SEARCH_USER_ERROR',
    
    LOGOUT:'LOGOUT',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_ERROR: 'LOGOUT_ERROR',

    // User
    UPDATE_USER: 'UPDATE_USER',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_ERROR: 'UPDATE_USER_ERROR',

    CREATE_USER:'CREATE_USER',
    CREATE_USER_SUCCESS:'CREATE_USER_SUCCESS',
    CREATE_USER_ERROR:'CREATE_USER_ERROR',

    ADD_RESPONSABILITY: 'ADD_RESPONSABILITY',
    ADD_RESPONSABILITY_SUCCESS: 'ADD_RESPONSABILITY_SUCCESS',
    ADD_RESPONSABILITY_ERROR: 'ADD_RESPONSABILITY_ERROR',

    DELETE_RESPONSABILITY: 'DELETE_RESPONSABILITY',
    DELETE_RESPONSABILITY_SUCCESS: 'DELETE_RESPONSABILITY_SUCCESS',
    DELETE_RESPONSABILITY_ERROR: 'DELETE_RESPONSABILITY_ERROR',


    GET_ALL_TAREAS:'GET_ALL_TAREAS',    
    GET_ALL_TAREAS_SUCCESS:'GET_ALL_TAREAS_SUCCESS',    
    GET_ALL_TAREAS_ERROR:'GET_ALL_TAREAS_ERROR',
    GET_ALL_USERS: 'GET_ALL_USERS',
    GET_ALL_USERS_SUCCESS: 'GET_ALL_USERS_SUCCESS',
    GET_ALL_USERS_ERROR: 'GET_ALL_USERS_ERROR',
    GET_ALL_ESTATUS: 'GET_ALL_ESTATUS',
    GET_ALL_ESTATUS_SUCCESS: 'GET_ALL_ESTATUS_SUCCESS',
    GET_ALL_ESTATUS_ERROR: 'GET_ALL_ESTATUS_ERROR',

    GET_ALL_TIPO_TAREA: 'GET_ALL_TIPO_TAREA',
    GET_ALL_TIPO_TAREA_SUCCESS: 'GET_ALL_TIPO_TAREA_SUCCESS',
    GET_ALL_TIPO_TAREA_ERROR: 'GET_ALL_TIPO_TAREA_ERROR',
    GET_ORDER_TAREAS : 'GET_ORDER_TAREAS',
    GET_ORDER_TAREAS_SUCCESS : 'GET_ORDER_TAREAS_SUCCESS',
    GET_ORDER_TAREAS_ERROR : 'GET_ORDER_TAREAS_ERROR',


    GET_ALL_PERSPECTIVAS: 'GET_ALL_PERSPECTIVAS',
    GET_ALL_PERSPECTIVAS_SUCCESS: 'GET_ALL_PERSPECTIVAS_SUCCESS',
    GET_ALL_PERSPECTIVAS_ERROR: 'GET_ALL_PERSPECTIVAS_ERROR',
    GET_PERSPECTIVA: 'GET_PERSPECTIVA',
    GET_PERSPECTIVA_SUCCESS: 'GET_PERSPECTIVA_SUCCESS',
    GET_PERSPECTIVA_ERROR: 'GET_PERSPECTIVA_ERROR',
    CREATE_PERSPECTIVA: 'CREATE_PERSPECTIVA',
    CREATE_PERSPECTIVA_SUCCESS: 'CREATE_PERSPECTIVA_SUCCESS',
    CREATE_PERSPECTIVA_ERROR: 'CREATE_PERSPECTIVA_ERROR',
    UPDATE_PERSPECTIVA: 'UPDATE_PERSPECTIVA',
    UPDATE_PERSPECTIVA_SUCCESS: 'UPDATE_PERSPECTIVA_SUCCESS',
    UPDATE_PERSPECTIVA_ERROR: 'UPDATE_PERSPECTIVA_ERROR',
    DELETE_PERSPECTIVA: 'DELETE_PERSPECTIVA',
    DELETE_PERSPECTIVA_SUCCESS: 'DELETE_PERSPECTIVA_SUCCESS',
    DELETE_PERSPECTIVA_ERROR: 'DELETE_PERSPECTIVA_ERROR',
    EDIT_PERSPECTIVA: 'EDIT_PERSPECTIVA',
    EDIT_PERSPECTIVA_SUCCESS: 'EDIT_PERSPECTIVA_SUCCESS',
    EDIT_PERSPECTIVA_ERROR: 'EDIT_PERSPECTIVA_ERROR',



    /// Áreas
    GET_ALL_AREAS:'GET_ALL_AREAS',
    GET_ALL_AREAS_SUCCESS:'GET_ALL_AREAS_SUCCESS',
    GET_ALL_AREAS_ERROR:'GET_ALL_AREAS_ERROR',

    CREATE_AREA : 'CREATE_AREA',
    CREATE_AREA_SUCCESS : 'CREATE_AREA_SUCCESS',
    CREATE_AREA_ERROR : 'CREATE_AREA_ERROR',

    EDIT_AREA: 'EDIT_AREA',
    EDIT_AREA_SUCCESS: 'EDIT_AREA_SUCCESS',
    EDIT_AREA_ERROR: 'EDIT_AREA_ERROR',
    EDIT_AREA_CANCEL: 'EDIT_AREA_CANCEL',

    UPDATE_AREA: 'UPDATE_AREA',
    UPDATE_AREA_SUCCESS: 'UPDATE_AREA_SUCCESS',
    UPDATE_AREA_ERROR: 'UPDATE_AREA_ERROR',
    
    DELETE_AREA: 'DELETE_AREA',
    DELETE_AREA_SUCCESS: 'DELETE_AREA_SUCCESS',
    DELETE_AREA_ERROR: 'DELETE_AREA_ERROR',
}




