export const types = {
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_ERROR:'LOGIN_ERROR',
    LOGIN_REQUEST:'LOGIN_REQUEST',

    LOGIN_VALIDATION_SUCCESS:'LOGIN_VALIDATION_SUCCESS',
    LOGIN_VALIDATION_ERROR:'LOGIN_VALIDATION_ERROR',

    GET_USER: 'GET_USER',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_ERROR: 'GET_USER_ERROR',
    SEARCH_USER: 'SEARCH_USER',
    SEARCH_USER_SUCCESS: 'SEARCH_USER_SUCCESS',
    SEARCH_USER_ERROR: 'SEARCH_USER_ERROR',
    
    LOGOUT:'LOGOUT',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_ERROR: 'LOGOUT_ERROR',


    // LOCATION
    GET_ESTADOS: 'GET_ESTADOS',
    GET_ESTADOS_SUCCESS: 'GET_ESTADOS_SUCCESS',
    GET_ESTADOS_ERROR: 'GET_ESTADOS_ERROR',
    GET_MUNICIPIOS: 'GET_MUNICIPIOS',
    GET_MUNICIPIOS_SUCCESS: 'GET_MUNICIPIOS_SUCCESS',
    GET_MUNICIPIOS_ERROR: 'GET_MUNICIPIOS_ERROR',

    // User
    UPDATE_USER: 'UPDATE_USER',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_ERROR: 'UPDATE_USER_ERROR',

    CREATE_USER:'CREATE_USER',
    CREATE_USER_SUCCESS:'CREATE_USER_SUCCESS',
    CREATE_USER_ERROR:'CREATE_USER_ERROR',

    GET_PROFILE:'GET_PROFILE',
    GET_PROFILE_SUCCESS:'GET_PROFILE_SUCCESS',
    GET_PROFILE_ERROR:'GET_PROFILE_ERROR',

    ADD_RESPONSABILITY: 'ADD_RESPONSABILITY',
    ADD_RESPONSABILITY_SUCCESS: 'ADD_RESPONSABILITY_SUCCESS',
    ADD_RESPONSABILITY_ERROR: 'ADD_RESPONSABILITY_ERROR',

    DELETE_RESPONSABILITY: 'DELETE_RESPONSABILITY',
    DELETE_RESPONSABILITY_SUCCESS: 'DELETE_RESPONSABILITY_SUCCESS',
    DELETE_RESPONSABILITY_ERROR: 'DELETE_RESPONSABILITY_ERROR',


    GET_ALL_TAREAS:'GET_ALL_TAREAS',    
    GET_ALL_TAREAS_SUCCESS:'GET_ALL_TAREAS_SUCCESS',    
    GET_ALL_TAREAS_ERROR:'GET_ALL_TAREAS_ERROR',
    GET_ALL_USERS: 'GET_ALL_USERS',
    GET_ALL_USERS_SUCCESS: 'GET_ALL_USERS_SUCCESS',
    GET_ALL_USERS_ERROR: 'GET_ALL_USERS_ERROR',
    GET_ALL_ESTATUS: 'GET_ALL_ESTATUS',
    GET_ALL_ESTATUS_SUCCESS: 'GET_ALL_ESTATUS_SUCCESS',
    GET_ALL_ESTATUS_ERROR: 'GET_ALL_ESTATUS_ERROR',

    GET_ALL_TIPO_TAREA: 'GET_ALL_TIPO_TAREA',
    GET_ALL_TIPO_TAREA_SUCCESS: 'GET_ALL_TIPO_TAREA_SUCCESS',
    GET_ALL_TIPO_TAREA_ERROR: 'GET_ALL_TIPO_TAREA_ERROR',
    GET_ORDER_TAREAS : 'GET_ORDER_TAREAS',
    GET_ORDER_TAREAS_SUCCESS : 'GET_ORDER_TAREAS_SUCCESS',
    GET_ORDER_TAREAS_ERROR : 'GET_ORDER_TAREAS_ERROR',


    GET_ALL_PERSPECTIVAS: 'GET_ALL_PERSPECTIVAS',
    GET_ALL_PERSPECTIVAS_SUCCESS: 'GET_ALL_PERSPECTIVAS_SUCCESS',
    GET_ALL_PERSPECTIVAS_ERROR: 'GET_ALL_PERSPECTIVAS_ERROR',
    GET_PERSPECTIVA: 'GET_PERSPECTIVA',
    GET_PERSPECTIVA_SUCCESS: 'GET_PERSPECTIVA_SUCCESS',
    GET_PERSPECTIVA_ERROR: 'GET_PERSPECTIVA_ERROR',
    CREATE_PERSPECTIVA: 'CREATE_PERSPECTIVA',
    CREATE_PERSPECTIVA_SUCCESS: 'CREATE_PERSPECTIVA_SUCCESS',
    CREATE_PERSPECTIVA_ERROR: 'CREATE_PERSPECTIVA_ERROR',
    UPDATE_PERSPECTIVA: 'UPDATE_PERSPECTIVA',
    UPDATE_PERSPECTIVA_SUCCESS: 'UPDATE_PERSPECTIVA_SUCCESS',
    UPDATE_PERSPECTIVA_ERROR: 'UPDATE_PERSPECTIVA_ERROR',
    DELETE_PERSPECTIVA: 'DELETE_PERSPECTIVA',
    DELETE_PERSPECTIVA_SUCCESS: 'DELETE_PERSPECTIVA_SUCCESS',
    DELETE_PERSPECTIVA_ERROR: 'DELETE_PERSPECTIVA_ERROR',
    EDIT_PERSPECTIVA: 'EDIT_PERSPECTIVA',
    EDIT_PERSPECTIVA_SUCCESS: 'EDIT_PERSPECTIVA_SUCCESS',
    EDIT_PERSPECTIVA_ERROR: 'EDIT_PERSPECTIVA_ERROR',



    /// Áreas
    GET_ALL_AREAS:'GET_ALL_AREAS',
    GET_ALL_AREAS_SUCCESS:'GET_ALL_AREAS_SUCCESS',
    GET_ALL_AREAS_ERROR:'GET_ALL_AREAS_ERROR',

    CREATE_AREA : 'CREATE_AREA',
    CREATE_AREA_SUCCESS : 'CREATE_AREA_SUCCESS',
    CREATE_AREA_ERROR : 'CREATE_AREA_ERROR',

    EDIT_AREA: 'EDIT_AREA',
    EDIT_AREA_SUCCESS: 'EDIT_AREA_SUCCESS',
    EDIT_AREA_ERROR: 'EDIT_AREA_ERROR',
    EDIT_AREA_CANCEL: 'EDIT_AREA_CANCEL',

    UPDATE_AREA: 'UPDATE_AREA',
    UPDATE_AREA_SUCCESS: 'UPDATE_AREA_SUCCESS',
    UPDATE_AREA_ERROR: 'UPDATE_AREA_ERROR',
    
    DELETE_AREA: 'DELETE_AREA',
    DELETE_AREA_SUCCESS: 'DELETE_AREA_SUCCESS',
    DELETE_AREA_ERROR: 'DELETE_AREA_ERROR',


    // Departamentos

    GET_ALL_DEPARTAMENTOS : 'GET_ALL_DEPARTAMENTOS',
    GET_ALL_DEPARTAMENTOS_SUCCESS : 'GET_ALL_DEPARTAMENTOS_SUCCESS',
    GET_ALL_DEPARTAMENTOS_ERROR : 'GET_ALL_DEPARTAMENTOS_ERROR',

    EDIT_DEPARTAMENTO : 'EDIT_DEPARTAMENTO',
    EDIT_DEPARTAMENTO_SUCCESS : 'EDIT_DEPARTAMENTO_SUCCESS',
    EDIT_DEPARTAMENTO_ERROR : 'EDIT_DEPARTAMENTO_ERROR',
    EDIT_DEPARTAMENTO_CANCEL : 'EDIT_DEPARTAMENTO_CANCEL',

    CREATE_DEPARTAMENTO : 'CREATE_DEPARTAMENTO',
    CREATE_DEPARTAMENTO_SUCCESS : 'CREATE_DEPARTAMENTO_SUCCESS',
    CREATE_DEPARTAMENTO_ERROR : 'CREATE_DEPARTAMENTO_ERROR',

    UPDATE_DEPARTAMENTO : 'UPDATE_DEPARTAMENTO',
    UPDATE_DEPARTAMENTO_SUCCESS : 'UPDATE_DEPARTAMENTO_SUCCESS',
    UPDATE_DEPARTAMENTO_ERROR : 'UPDATE_DEPARTAMENTO_ERROR',

    DELETE_DEPARTAMENTO : 'DELETE_DEPARTAMENTO',
    DELETE_DEPARTAMENTO_SUCCESS : 'DELETE_DEPARTAMENTO_SUCCESS',
    DELETE_DEPARTAMENTO_ERROR : 'DELETE_DEPARTAMENTO_ERROR',


    GET_ALL_PUESTOS : 'GET_ALL_PUESTOS',
    GET_ALL_PUESTOS_SUCCESS : 'GET_ALL_PUESTOS_SUCCESS',
    GET_ALL_PUESTOS_ERROR : 'GET_ALL_PUESTOS_ERROR',

    EDIT_PUESTO : 'EDIT_PUESTO',
    EDIT_PUESTO_SUCCESS : 'EDIT_PUESTO_SUCCESS',
    EDIT_PUESTO_ERROR : 'EDIT_PUESTO_ERROR',
    EDIT_PUESTO_CANCEL : 'EDIT_PUESTO_CANCEL',

    CREATE_PUESTO : 'CREATE_PUESTO',
    CREATE_PUESTO_SUCCESS : 'CREATE_PUESTO_SUCCESS',
    CREATE_PUESTO_ERROR : 'CREATE_PUESTO_ERROR',

    UPDATE_PUESTO : 'UPDATE_PUESTO',
    UPDATE_PUESTO_SUCCESS : 'UPDATE_PUESTO_SUCCESS',
    UPDATE_PUESTO_ERROR : 'UPDATE_PUESTO_ERROR',

    DELETE_PUESTO : 'DELETE_PUESTO',
    DELETE_PUESTO_SUCCESS : 'DELETE_PUESTO_SUCCESS',
    DELETE_PUESTO_ERROR : 'DELETE_PUESTO_ERROR',
    

    // Somos Devarana
    GET_CORPORATIVO: 'GET_CORPORATIVO',
    GET_CORPORATIVO_SUCCESS: 'GET_CORPORATIVO_SUCCESS',
    GET_CORPORATIVO_ERROR: 'GET_CORPORATIVO_ERROR',
    UPDATE_CORPORATIVO: 'UPDATE_CORPORATIVO',
    UPDATE_CORPORATIVO_SUCCESS: 'UPDATE_CORPORATIVO_SUCCESS',
    UPDATE_CORPORATIVO_ERROR: 'UPDATE_CORPORATIVO_ERROR',
}





