export const types = {
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAILURE:'LOGIN_FAILURE',
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGOUT:'LOGOUT',
    GET_ALL_TAREAS:'GET_ALL_TAREAS',    
    GET_ALL_TAREAS_SUCCESS:'GET_ALL_TAREAS_SUCCESS',    
    GET_ALL_TAREAS_ERROR:'GET_ALL_TAREAS_ERROR',
    GET_ALL_USERS: 'GET_ALL_USERS',
    GET_ALL_USERS_SUCCESS: 'GET_ALL_USERS_SUCCESS',
    GET_ALL_USERS_ERROR: 'GET_ALL_USERS_ERROR',
    GET_ALL_ESTATUS: 'GET_ALL_ESTATUS',
    GET_ALL_ESTATUS_SUCCESS: 'GET_ALL_ESTATUS_SUCCESS',
    GET_ALL_ESTATUS_ERROR: 'GET_ALL_ESTATUS_ERROR',

    GET_ALL_TIPO_TAREA: 'GET_ALL_TIPO_TAREA',
    GET_ALL_TIPO_TAREA_SUCCESS: 'GET_ALL_TIPO_TAREA_SUCCESS',
    GET_ALL_TIPO_TAREA_ERROR: 'GET_ALL_TIPO_TAREA_ERROR',
    GET_ORDER_TAREAS : 'GET_ORDER_TAREAS',
    GET_ORDER_TAREAS_SUCCESS : 'GET_ORDER_TAREAS_SUCCESS',
    GET_ORDER_TAREAS_ERROR : 'GET_ORDER_TAREAS_ERROR',
}


